### ISSUE TITLE
TexLive und TeXlipse Beschreibung hinzufügen

### ISSUE THREAD

**Issue by dav1d-wright** [HSR-Stud/VorlageZFLaTex#1]
Ich würde hier noch eine Beschreibung für TeXlipse und TexLive hinzufügen. Für Nueinsteiger, die häufig schon Erfahrung mit Eclipse haben, war es sehr hilfreich, dass man einfach ein bestehendes Projekt clonen und dann in Eclipse importieren konnte.

**Comment by LMazzole** [comment]
Die wäre vemutlich im Repo [Willkommen](https://github.com/HSR-Stud/Willkommen) besser aufgehoben. Die Anleitung hier ist eigentlich nur noch ein überbleibsel und könnte entfernt werden.

**Comment by dav1d-wright** [comment]
Stimmt natürlich, danke für den Hinweis.

**Comment by pescara** [comment]
Ich würde damit hier den Issue "closen" -> Er ist ja nochmals bei Willkommen erfasst.

**Comment by dav1d-wright** [comment]
@pescara agreed
