### ISSUE TITLE
Beispiel für das "Einbinden" von Submodulen ergänzen?

### ISSUE THREAD

**Issue by pescara** [HSR-Stud/VorlageZFLaTex#3]
Wollen wir noch das Einbinden eines Submodules (z.B. header, idiotenseite oder travis) im Repo einfügen?

**Comment by pescara** [comment]
Travis sollte hier so oder so unbedingt als Submodule eingebunden werden....

**Comment by LMazzole** [comment]
Erledigt mit Commit  683dabf
