### ISSUE TITLE
Einfügen der Latex-Kursunterlagen

### ISSUE THREAD

**Issue by pescara** [HSR-Stud/VorlageZFLaTex#4]
Wollen wir hier noch sämtliche Latex-Kursunterlagen einfügen?
Eventuell bei den Latex-Kursunterlagen gleich inklusive der Source-Files & PowerPoints?

**Comment by LMazzole** [comment]
Ich würde die Vorlage nicht zu fest Aufblasen und sie nur mit Minimalbeispielen ausstatten.  
Für den LaTex-Kurs finde ich ein eigens Repo sinnvoller. So empfinde ich es als zu unüberischtlich.
