### ISSUE TITLE
Header als Submodule

### ISSUE THREAD

**Issue by dav1d-wright** [HSR-Stud/VorlageZFLaTex#6]
Ich bin der Meinung, dass man auch den Header hier als Submodule hinzufügen sollte.

**Comment by LMazzole** [comment]
Ich verstehe, dass man keinen doppelten Code haben sollte. Jedoch sehe ich bei dem <header als Submodule ein Problem mit der Rückwärtskompatibilität da eine Änderung im Header-Submodule Auswirkungen auf alle Repos hat, oder irre ich mich da?

**Comment by dav1d-wright** [comment]
Jein, ganz unrecht hast du nicht. Jedoch hat ein Git Repo zu jeder Zeit einen definierten Stand von einem Submodul. Wenn man z.B.  Änderungen im Header committet werden die nicht automatisch in alle Repos einfliessen. Verwalter dieser Repos (z.B. von VorlageZFLaTex) müssen aktiv diese Änderungen in ihr Repo "holen" und diesen neuen Stand committen, falls sie das möchten. Aber der Grundgedanke dahinter ist natürlich schon, dass der Header zentral verwaltet wird, so dass alle Zusammenfassungen etwa gleich aussehen. Deshalb wurde er damals auch erstellt.
